# Generated by Django 5.0.1 on 2025-11-21 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwc_admin', '0002_allowlist_natneg_profile_aim_profile_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysteryGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, help_text='Mystery Gift filename (e.g., 154p.myg)', max_length=255, unique=True)),
                ('file', models.FileField(help_text='Upload .myg file', upload_to='mystery_gifts/')),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes (auto-populated)')),
                ('game_id', models.CharField(db_index=True, help_text='Game ID (e.g., CPUE for Pokemon Platinum USA)', max_length=10)),
                ('title', models.CharField(help_text="Display name (e.g., 'Secret Key Event')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Event description')),
                ('event_type', models.CharField(blank=True, help_text="Type of event (e.g., 'Pokemon', 'Item', 'Unlock')", max_length=50)),
                ('region', models.CharField(blank=True, help_text='Region code (US, EU, JP, etc.)', max_length=10)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this gift is currently available for download')),
                ('start_date', models.DateTimeField(blank=True, help_text='When this gift becomes available (optional)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When this gift expires (optional)', null=True)),
                ('download_count', models.IntegerField(default=0, help_text='Number of times downloaded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Admin who created this', max_length=50)),
            ],
            options={
                'verbose_name': 'Mystery Gift',
                'verbose_name_plural': 'Mystery Gifts',
                'db_table': 'mystery_gifts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['game_id', 'enabled'], name='mystery_gif_game_id_abf86c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MysteryGiftDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, help_text='Client user agent', max_length=255)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('mystery_gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='dwc_admin.mysterygift')),
                ('profile', models.ForeignKey(blank=True, help_text='User who downloaded (if tracked)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mystery_gifts_received', to='dwc_admin.profile')),
            ],
            options={
                'verbose_name': 'Mystery Gift Download',
                'verbose_name_plural': 'Mystery Gift Downloads',
                'db_table': 'mystery_gift_downloads',
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['mystery_gift', 'downloaded_at'], name='mystery_gif_mystery_d79378_idx')],
            },
        ),
    ]
