# Generated by Django 5.0.1 on 2025-11-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwc_admin', '0003_mysterygift_mysterygiftdownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDistributionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(db_index=True, help_text='Game ID (e.g., CPUD for Pokemon Platinum Germany)', max_length=10, unique=True)),
                ('distribution_mode', models.CharField(choices=[('random', 'Random - Pick one random gift from available'), ('priority', 'Priority - Pick highest priority gift'), ('all', 'All - Show all gifts (for non-Pokemon games)')], default='random', help_text='How to select which gift to give to the user', max_length=20)),
                ('track_downloads', models.BooleanField(default=True, help_text='Track which gifts users have already received (prevents duplicates)')),
                ('reset_on_completion', models.BooleanField(default=True, help_text='When user has all gifts, reset and allow re-downloading')),
            ],
            options={
                'verbose_name': 'Game Distribution Setting',
                'verbose_name_plural': 'Game Distribution Settings',
                'db_table': 'game_distribution_settings',
                'ordering': ['game_id'],
            },
        ),
        migrations.AddField(
            model_name='mysterygift',
            name='priority',
            field=models.IntegerField(default=0, help_text="Priority for distribution (higher = more important). Used when distribution_mode is 'priority'"),
        ),
        migrations.AddIndex(
            model_name='mysterygiftdownload',
            index=models.Index(fields=['profile', 'downloaded_at'], name='mystery_gif_profile_8a7925_idx'),
        ),
    ]
